# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafic.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_t(object):
    def setupUi(self, t):
        t.setObjectName("t")
        t.resize(936, 836)
        t.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.centralWidget = QtWidgets.QWidget(t)
        self.centralWidget.setObjectName("centralWidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 30, 841, 741))
        self.stackedWidget.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginpage = QtWidgets.QWidget()
        self.loginpage.setObjectName("loginpage")
        self.widget = QtWidgets.QWidget(self.loginpage)
        self.widget.setGeometry(QtCore.QRect(0, 0, 851, 741))
        self.widget.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 40, 701, 651))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(410, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.login_btn1 = QtWidgets.QPushButton(self.groupBox_2)
        self.login_btn1.setGeometry(QtCore.QRect(350, 390, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn1.setFont(font)
        self.login_btn1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.login_btn1.setObjectName("login_btn1")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(420, 250, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.sabtenam_btn1 = QtWidgets.QPushButton(self.groupBox_2)
        self.sabtenam_btn1.setGeometry(QtCore.QRect(230, 390, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabtenam_btn1.setFont(font)
        self.sabtenam_btn1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sabtenam_btn1.setObjectName("sabtenam_btn1")
        self.graphicsView_20 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_20.setGeometry(QtCore.QRect(120, 110, 431, 451))
        self.graphicsView_20.setObjectName("graphicsView_20")
        self.name_in1 = QtWidgets.QTextEdit(self.groupBox_2)
        self.name_in1.setGeometry(QtCore.QRect(190, 180, 171, 31))
        self.name_in1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_in1.setObjectName("name_in1")
        self.password_in1 = QtWidgets.QTextEdit(self.groupBox_2)
        self.password_in1.setGeometry(QtCore.QRect(190, 250, 171, 31))
        self.password_in1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_in1.setObjectName("password_in1")
        self.graphicsView_20.raise_()
        self.label_6.raise_()
        self.login_btn1.raise_()
        self.label_8.raise_()
        self.sabtenam_btn1.raise_()
        self.name_in1.raise_()
        self.password_in1.raise_()
        self.stackedWidget.addWidget(self.loginpage)
        self.nextpage = QtWidgets.QWidget()
        self.nextpage.setObjectName("nextpage")
        self.widget_2 = QtWidgets.QWidget(self.nextpage)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 841, 731))
        self.widget_2.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox.setGeometry(QtCore.QRect(90, 60, 661, 631))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(410, 160, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(430, 100, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(430, 220, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(420, 270, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(440, 330, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.sabtenam_btn2 = QtWidgets.QPushButton(self.groupBox)
        self.sabtenam_btn2.setGeometry(QtCore.QRect(280, 460, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabtenam_btn2.setFont(font)
        self.sabtenam_btn2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sabtenam_btn2.setObjectName("sabtenam_btn2")
        self.graphicsView_21 = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_21.setGeometry(QtCore.QRect(100, 61, 461, 511))
        self.graphicsView_21.setObjectName("graphicsView_21")
        self.name_in2 = QtWidgets.QTextEdit(self.groupBox)
        self.name_in2.setGeometry(QtCore.QRect(160, 100, 171, 31))
        self.name_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_in2.setObjectName("name_in2")
        self.family_in2 = QtWidgets.QTextEdit(self.groupBox)
        self.family_in2.setGeometry(QtCore.QRect(160, 160, 171, 31))
        self.family_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.family_in2.setObjectName("family_in2")
        self.ssn_in2 = QtWidgets.QTextEdit(self.groupBox)
        self.ssn_in2.setGeometry(QtCore.QRect(160, 220, 171, 31))
        self.ssn_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ssn_in2.setObjectName("ssn_in2")
        self.email_in2 = QtWidgets.QTextEdit(self.groupBox)
        self.email_in2.setGeometry(QtCore.QRect(160, 270, 171, 31))
        self.email_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email_in2.setObjectName("email_in2")
        self.password_in2 = QtWidgets.QTextEdit(self.groupBox)
        self.password_in2.setGeometry(QtCore.QRect(160, 330, 171, 31))
        self.password_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_in2.setObjectName("password_in2")
        self.graphicsView_21.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.sabtenam_btn2.raise_()
        self.name_in2.raise_()
        self.family_in2.raise_()
        self.ssn_in2.raise_()
        self.email_in2.raise_()
        self.password_in2.raise_()
        self.stackedWidget.addWidget(self.nextpage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(620, 0, 211, 731))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.snap_btn1 = QtWidgets.QPushButton(self.frame)
        self.snap_btn1.setGeometry(QtCore.QRect(60, 490, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.snap_btn1.setFont(font)
        self.snap_btn1.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.snap_btn1.setObjectName("snap_btn1")
        self.taghir_btn1 = QtWidgets.QPushButton(self.frame)
        self.taghir_btn1.setGeometry(QtCore.QRect(60, 330, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.taghir_btn1.setFont(font)
        self.taghir_btn1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.taghir_btn1.setObjectName("taghir_btn1")
        self.ijad_btn1 = QtWidgets.QPushButton(self.frame)
        self.ijad_btn1.setGeometry(QtCore.QRect(60, 250, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ijad_btn1.setFont(font)
        self.ijad_btn1.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.ijad_btn1.setObjectName("ijad_btn1")
        self.sabtenam_btn3 = QtWidgets.QPushButton(self.frame)
        self.sabtenam_btn3.setGeometry(QtCore.QRect(60, 100, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabtenam_btn3.setFont(font)
        self.sabtenam_btn3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.sabtenam_btn3.setObjectName("sabtenam_btn3")
        self.price_btn1 = QtWidgets.QPushButton(self.frame)
        self.price_btn1.setGeometry(QtCore.QRect(60, 410, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.price_btn1.setFont(font)
        self.price_btn1.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.price_btn1.setObjectName("price_btn1")
        self.login_btn4 = QtWidgets.QPushButton(self.frame)
        self.login_btn4.setGeometry(QtCore.QRect(60, 20, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn4.setFont(font)
        self.login_btn4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn4.setObjectName("login_btn4")
        self.ticket_btn1 = QtWidgets.QPushButton(self.frame)
        self.ticket_btn1.setGeometry(QtCore.QRect(60, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ticket_btn1.setFont(font)
        self.ticket_btn1.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.ticket_btn1.setObjectName("ticket_btn1")
        self.wallet_btn1 = QtWidgets.QPushButton(self.frame)
        self.wallet_btn1.setGeometry(QtCore.QRect(60, 170, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wallet_btn1.setFont(font)
        self.wallet_btn1.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.wallet_btn1.setObjectName("wallet_btn1")
        self.gozaresh_btn1 = QtWidgets.QPushButton(self.frame)
        self.gozaresh_btn1.setGeometry(QtCore.QRect(60, 650, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gozaresh_btn1.setFont(font)
        self.gozaresh_btn1.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.gozaresh_btn1.setObjectName("gozaresh_btn1")
        self.widget_3 = QtWidgets.QWidget(self.page)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 621, 611))
        self.widget_3.setObjectName("widget_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget_3)
        self.graphicsView.setGeometry(QtCore.QRect(66, 50, 491, 521))
        self.graphicsView.setObjectName("graphicsView")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(410, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.widget_3)
        self.line.setGeometry(QtCore.QRect(120, 100, 391, 31))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.afzayesh_mojodi_btn = QtWidgets.QPushButton(self.widget_3)
        self.afzayesh_mojodi_btn.setGeometry(QtCore.QRect(240, 460, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.afzayesh_mojodi_btn.setFont(font)
        self.afzayesh_mojodi_btn.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.afzayesh_mojodi_btn.setObjectName("afzayesh_mojodi_btn")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.widget_3)
        self.graphicsView_2.setGeometry(QtCore.QRect(120, 170, 391, 241))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.listWidget_4 = QtWidgets.QListWidget(self.widget_3)
        self.listWidget_4.setGeometry(QtCore.QRect(220, 320, 141, 31))
        self.listWidget_4.setObjectName("listWidget_4")
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        self.label_16.setGeometry(QtCore.QRect(370, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.widget_3)
        self.label_15.setGeometry(QtCore.QRect(130, 320, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.listWidget_3 = QtWidgets.QListWidget(self.widget_3)
        self.listWidget_3.setGeometry(QtCore.QRect(220, 240, 141, 31))
        self.listWidget_3.setObjectName("listWidget_3")
        self.label_17 = QtWidgets.QLabel(self.widget_3)
        self.label_17.setGeometry(QtCore.QRect(400, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_14 = QtWidgets.QLabel(self.widget_3)
        self.label_14.setGeometry(QtCore.QRect(130, 240, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_4.setGeometry(QtCore.QRect(310, 10, 291, 231))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setGeometry(QtCore.QRect(340, 50, 241, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(480, 70, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(500, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(490, 120, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(490, 150, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setGeometry(QtCore.QRect(450, 180, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_2)
        self.label_20.setGeometry(QtCore.QRect(460, 210, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_2)
        self.label_21.setGeometry(QtCore.QRect(350, 100, 55, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_2)
        self.label_22.setGeometry(QtCore.QRect(350, 150, 55, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_2)
        self.label_23.setGeometry(QtCore.QRect(350, 130, 55, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page_2)
        self.label_24.setGeometry(QtCore.QRect(350, 180, 55, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.page_2)
        self.label_25.setGeometry(QtCore.QRect(350, 210, 55, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.page_2)
        self.label_26.setGeometry(QtCore.QRect(350, 80, 55, 16))
        self.label_26.setObjectName("label_26")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_5.setGeometry(QtCore.QRect(10, 10, 291, 231))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.label_38 = QtWidgets.QLabel(self.page_2)
        self.label_38.setGeometry(QtCore.QRect(50, 180, 55, 16))
        self.label_38.setObjectName("label_38")
        self.label_125 = QtWidgets.QLabel(self.page_2)
        self.label_125.setGeometry(QtCore.QRect(180, 70, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_125.setFont(font)
        self.label_125.setObjectName("label_125")
        self.label_33 = QtWidgets.QLabel(self.page_2)
        self.label_33.setGeometry(QtCore.QRect(50, 210, 55, 16))
        self.label_33.setObjectName("label_33")
        self.line_9 = QtWidgets.QFrame(self.page_2)
        self.line_9.setGeometry(QtCore.QRect(40, 50, 241, 20))
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_32 = QtWidgets.QLabel(self.page_2)
        self.label_32.setGeometry(QtCore.QRect(50, 130, 55, 16))
        self.label_32.setObjectName("label_32")
        self.label_36 = QtWidgets.QLabel(self.page_2)
        self.label_36.setGeometry(QtCore.QRect(160, 210, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_126 = QtWidgets.QLabel(self.page_2)
        self.label_126.setGeometry(QtCore.QRect(50, 80, 55, 16))
        self.label_126.setObjectName("label_126")
        self.label_34 = QtWidgets.QLabel(self.page_2)
        self.label_34.setGeometry(QtCore.QRect(50, 100, 55, 16))
        self.label_34.setObjectName("label_34")
        self.label_31 = QtWidgets.QLabel(self.page_2)
        self.label_31.setGeometry(QtCore.QRect(190, 150, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_27 = QtWidgets.QLabel(self.page_2)
        self.label_27.setGeometry(QtCore.QRect(150, 180, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_30 = QtWidgets.QLabel(self.page_2)
        self.label_30.setGeometry(QtCore.QRect(200, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_30.setObjectName("label_30")
        self.label_28 = QtWidgets.QLabel(self.page_2)
        self.label_28.setGeometry(QtCore.QRect(190, 120, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.page_2)
        self.label_29.setGeometry(QtCore.QRect(50, 150, 55, 16))
        self.label_29.setObjectName("label_29")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_7.setGeometry(QtCore.QRect(310, 250, 291, 231))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_8.setGeometry(QtCore.QRect(10, 250, 291, 231))
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_6.setGeometry(QtCore.QRect(10, 490, 291, 231))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_15 = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_15.setGeometry(QtCore.QRect(310, 490, 291, 231))
        self.graphicsView_15.setObjectName("graphicsView_15")
        self.label_40 = QtWidgets.QLabel(self.page_2)
        self.label_40.setGeometry(QtCore.QRect(450, 420, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.page_2)
        self.label_41.setGeometry(QtCore.QRect(490, 360, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.page_2)
        self.label_42.setGeometry(QtCore.QRect(350, 390, 55, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.page_2)
        self.label_43.setGeometry(QtCore.QRect(500, 340, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.page_2)
        self.label_44.setGeometry(QtCore.QRect(490, 390, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.line_4 = QtWidgets.QFrame(self.page_2)
        self.line_4.setGeometry(QtCore.QRect(340, 290, 241, 20))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_45 = QtWidgets.QLabel(self.page_2)
        self.label_45.setGeometry(QtCore.QRect(350, 370, 55, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.page_2)
        self.label_46.setGeometry(QtCore.QRect(350, 450, 55, 16))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.page_2)
        self.label_47.setGeometry(QtCore.QRect(350, 340, 55, 16))
        self.label_47.setObjectName("label_47")
        self.label_49 = QtWidgets.QLabel(self.page_2)
        self.label_49.setGeometry(QtCore.QRect(460, 450, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.page_2)
        self.label_50.setGeometry(QtCore.QRect(480, 310, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.page_2)
        self.label_51.setGeometry(QtCore.QRect(350, 420, 55, 16))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.page_2)
        self.label_52.setGeometry(QtCore.QRect(350, 320, 55, 16))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.page_2)
        self.label_53.setGeometry(QtCore.QRect(150, 420, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.page_2)
        self.label_54.setGeometry(QtCore.QRect(190, 360, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.page_2)
        self.label_55.setGeometry(QtCore.QRect(50, 390, 55, 16))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.page_2)
        self.label_56.setGeometry(QtCore.QRect(200, 340, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.page_2)
        self.label_57.setGeometry(QtCore.QRect(190, 390, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.line_5 = QtWidgets.QFrame(self.page_2)
        self.line_5.setGeometry(QtCore.QRect(40, 290, 241, 20))
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_58 = QtWidgets.QLabel(self.page_2)
        self.label_58.setGeometry(QtCore.QRect(50, 370, 55, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.page_2)
        self.label_59.setGeometry(QtCore.QRect(50, 450, 55, 16))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.page_2)
        self.label_60.setGeometry(QtCore.QRect(50, 340, 55, 16))
        self.label_60.setObjectName("label_60")
        self.label_62 = QtWidgets.QLabel(self.page_2)
        self.label_62.setGeometry(QtCore.QRect(160, 450, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.page_2)
        self.label_63.setGeometry(QtCore.QRect(180, 310, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.page_2)
        self.label_64.setGeometry(QtCore.QRect(50, 420, 55, 16))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.page_2)
        self.label_65.setGeometry(QtCore.QRect(50, 320, 55, 16))
        self.label_65.setObjectName("label_65")
        self.label_128 = QtWidgets.QLabel(self.page_2)
        self.label_128.setGeometry(QtCore.QRect(450, 660, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_128.setFont(font)
        self.label_128.setObjectName("label_128")
        self.label_129 = QtWidgets.QLabel(self.page_2)
        self.label_129.setGeometry(QtCore.QRect(490, 600, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_129.setFont(font)
        self.label_129.setObjectName("label_129")
        self.label_130 = QtWidgets.QLabel(self.page_2)
        self.label_130.setGeometry(QtCore.QRect(350, 630, 55, 16))
        self.label_130.setObjectName("label_130")
        self.label_131 = QtWidgets.QLabel(self.page_2)
        self.label_131.setGeometry(QtCore.QRect(500, 580, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_131.setFont(font)
        self.label_131.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_131.setObjectName("label_131")
        self.label_132 = QtWidgets.QLabel(self.page_2)
        self.label_132.setGeometry(QtCore.QRect(490, 630, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_132.setFont(font)
        self.label_132.setObjectName("label_132")
        self.line_10 = QtWidgets.QFrame(self.page_2)
        self.line_10.setGeometry(QtCore.QRect(340, 530, 241, 20))
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_133 = QtWidgets.QLabel(self.page_2)
        self.label_133.setGeometry(QtCore.QRect(350, 610, 55, 16))
        self.label_133.setObjectName("label_133")
        self.label_134 = QtWidgets.QLabel(self.page_2)
        self.label_134.setGeometry(QtCore.QRect(350, 690, 55, 16))
        self.label_134.setObjectName("label_134")
        self.label_135 = QtWidgets.QLabel(self.page_2)
        self.label_135.setGeometry(QtCore.QRect(350, 580, 55, 16))
        self.label_135.setObjectName("label_135")
        self.label_137 = QtWidgets.QLabel(self.page_2)
        self.label_137.setGeometry(QtCore.QRect(460, 690, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_137.setFont(font)
        self.label_137.setObjectName("label_137")
        self.label_138 = QtWidgets.QLabel(self.page_2)
        self.label_138.setGeometry(QtCore.QRect(480, 550, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_138.setFont(font)
        self.label_138.setObjectName("label_138")
        self.label_139 = QtWidgets.QLabel(self.page_2)
        self.label_139.setGeometry(QtCore.QRect(350, 660, 55, 16))
        self.label_139.setObjectName("label_139")
        self.label_140 = QtWidgets.QLabel(self.page_2)
        self.label_140.setGeometry(QtCore.QRect(350, 560, 55, 16))
        self.label_140.setObjectName("label_140")
        self.label_141 = QtWidgets.QLabel(self.page_2)
        self.label_141.setGeometry(QtCore.QRect(150, 660, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_141.setFont(font)
        self.label_141.setObjectName("label_141")
        self.label_142 = QtWidgets.QLabel(self.page_2)
        self.label_142.setGeometry(QtCore.QRect(190, 600, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_142.setFont(font)
        self.label_142.setObjectName("label_142")
        self.label_143 = QtWidgets.QLabel(self.page_2)
        self.label_143.setGeometry(QtCore.QRect(50, 630, 55, 16))
        self.label_143.setObjectName("label_143")
        self.label_144 = QtWidgets.QLabel(self.page_2)
        self.label_144.setGeometry(QtCore.QRect(200, 580, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_144.setFont(font)
        self.label_144.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_144.setObjectName("label_144")
        self.label_145 = QtWidgets.QLabel(self.page_2)
        self.label_145.setGeometry(QtCore.QRect(190, 630, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_145.setFont(font)
        self.label_145.setObjectName("label_145")
        self.line_11 = QtWidgets.QFrame(self.page_2)
        self.line_11.setGeometry(QtCore.QRect(40, 530, 241, 20))
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_146 = QtWidgets.QLabel(self.page_2)
        self.label_146.setGeometry(QtCore.QRect(50, 610, 55, 16))
        self.label_146.setObjectName("label_146")
        self.label_147 = QtWidgets.QLabel(self.page_2)
        self.label_147.setGeometry(QtCore.QRect(50, 690, 55, 16))
        self.label_147.setObjectName("label_147")
        self.label_148 = QtWidgets.QLabel(self.page_2)
        self.label_148.setGeometry(QtCore.QRect(50, 580, 55, 16))
        self.label_148.setObjectName("label_148")
        self.label_150 = QtWidgets.QLabel(self.page_2)
        self.label_150.setGeometry(QtCore.QRect(160, 690, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_150.setFont(font)
        self.label_150.setObjectName("label_150")
        self.label_151 = QtWidgets.QLabel(self.page_2)
        self.label_151.setGeometry(QtCore.QRect(180, 550, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_151.setFont(font)
        self.label_151.setObjectName("label_151")
        self.label_152 = QtWidgets.QLabel(self.page_2)
        self.label_152.setGeometry(QtCore.QRect(50, 660, 55, 16))
        self.label_152.setObjectName("label_152")
        self.label_153 = QtWidgets.QLabel(self.page_2)
        self.label_153.setGeometry(QtCore.QRect(50, 560, 55, 16))
        self.label_153.setObjectName("label_153")
        self.checkBox = QtWidgets.QCheckBox(self.page_2)
        self.checkBox.setGeometry(QtCore.QRect(510, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_2.setGeometry(QtCore.QRect(210, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_3.setGeometry(QtCore.QRect(500, 260, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_4.setGeometry(QtCore.QRect(210, 260, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_5.setGeometry(QtCore.QRect(510, 500, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_6.setGeometry(QtCore.QRect(210, 500, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.ijad_btn2 = QtWidgets.QPushButton(self.page_2)
        self.ijad_btn2.setGeometry(QtCore.QRect(680, 260, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ijad_btn2.setFont(font)
        self.ijad_btn2.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.ijad_btn2.setObjectName("ijad_btn2")
        self.taghir_btn2 = QtWidgets.QPushButton(self.page_2)
        self.taghir_btn2.setGeometry(QtCore.QRect(680, 340, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.taghir_btn2.setFont(font)
        self.taghir_btn2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.taghir_btn2.setObjectName("taghir_btn2")
        self.ticket_btn2 = QtWidgets.QPushButton(self.page_2)
        self.ticket_btn2.setGeometry(QtCore.QRect(680, 580, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ticket_btn2.setFont(font)
        self.ticket_btn2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.ticket_btn2.setObjectName("ticket_btn2")
        self.price_btn2 = QtWidgets.QPushButton(self.page_2)
        self.price_btn2.setGeometry(QtCore.QRect(680, 420, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.price_btn2.setFont(font)
        self.price_btn2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.price_btn2.setObjectName("price_btn2")
        self.sabtenam_btn4 = QtWidgets.QPushButton(self.page_2)
        self.sabtenam_btn4.setGeometry(QtCore.QRect(680, 110, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabtenam_btn4.setFont(font)
        self.sabtenam_btn4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.sabtenam_btn4.setObjectName("sabtenam_btn4")
        self.gozaresh_btn2 = QtWidgets.QPushButton(self.page_2)
        self.gozaresh_btn2.setGeometry(QtCore.QRect(680, 660, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gozaresh_btn2.setFont(font)
        self.gozaresh_btn2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.gozaresh_btn2.setObjectName("gozaresh_btn2")
        self.wallet_btn2 = QtWidgets.QPushButton(self.page_2)
        self.wallet_btn2.setGeometry(QtCore.QRect(680, 180, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wallet_btn2.setFont(font)
        self.wallet_btn2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.wallet_btn2.setObjectName("wallet_btn2")
        self.login_btn3 = QtWidgets.QPushButton(self.page_2)
        self.login_btn3.setGeometry(QtCore.QRect(680, 30, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn3.setFont(font)
        self.login_btn3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn3.setObjectName("login_btn3")
        self.snap_btn2 = QtWidgets.QPushButton(self.page_2)
        self.snap_btn2.setGeometry(QtCore.QRect(680, 500, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.snap_btn2.setFont(font)
        self.snap_btn2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.snap_btn2.setObjectName("snap_btn2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.graphicsView_16 = QtWidgets.QGraphicsView(self.page_5)
        self.graphicsView_16.setGeometry(QtCore.QRect(60, 30, 531, 621))
        self.graphicsView_16.setObjectName("graphicsView_16")
        self.label_10 = QtWidgets.QLabel(self.page_5)
        self.label_10.setGeometry(QtCore.QRect(490, 50, 55, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_48 = QtWidgets.QLabel(self.page_5)
        self.label_48.setGeometry(QtCore.QRect(380, 380, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_61 = QtWidgets.QLabel(self.page_5)
        self.label_61.setGeometry(QtCore.QRect(430, 250, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_127 = QtWidgets.QLabel(self.page_5)
        self.label_127.setGeometry(QtCore.QRect(440, 190, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_127.setFont(font)
        self.label_127.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_127.setObjectName("label_127")
        self.label_136 = QtWidgets.QLabel(self.page_5)
        self.label_136.setGeometry(QtCore.QRect(430, 310, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_136.setFont(font)
        self.label_136.setObjectName("label_136")
        self.line_12 = QtWidgets.QFrame(self.page_5)
        self.line_12.setGeometry(QtCore.QRect(80, 90, 461, 20))
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_149 = QtWidgets.QLabel(self.page_5)
        self.label_149.setGeometry(QtCore.QRect(400, 440, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_149.setFont(font)
        self.label_149.setObjectName("label_149")
        self.label_154 = QtWidgets.QLabel(self.page_5)
        self.label_154.setGeometry(QtCore.QRect(420, 130, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_154.setFont(font)
        self.label_154.setObjectName("label_154")
        self.label_155 = QtWidgets.QLabel(self.page_5)
        self.label_155.setGeometry(QtCore.QRect(350, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_155.setFont(font)
        self.label_155.setObjectName("label_155")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 520, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_84 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_84.setGeometry(QtCore.QRect(680, 500, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_84.setFont(font)
        self.pushButton_84.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_84.setObjectName("pushButton_84")
        self.login_btn2_16 = QtWidgets.QPushButton(self.page_5)
        self.login_btn2_16.setGeometry(QtCore.QRect(680, 30, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn2_16.setFont(font)
        self.login_btn2_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn2_16.setObjectName("login_btn2_16")
        self.pushButton_79 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_79.setGeometry(QtCore.QRect(680, 260, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_79.setFont(font)
        self.pushButton_79.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_79.setObjectName("pushButton_79")
        self.wallet_btn_12 = QtWidgets.QPushButton(self.page_5)
        self.wallet_btn_12.setGeometry(QtCore.QRect(680, 180, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wallet_btn_12.setFont(font)
        self.wallet_btn_12.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.wallet_btn_12.setObjectName("wallet_btn_12")
        self.sabtenam_btn3_12 = QtWidgets.QPushButton(self.page_5)
        self.sabtenam_btn3_12.setGeometry(QtCore.QRect(680, 110, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabtenam_btn3_12.setFont(font)
        self.sabtenam_btn3_12.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.sabtenam_btn3_12.setObjectName("sabtenam_btn3_12")
        self.pushButton_82 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_82.setGeometry(QtCore.QRect(680, 420, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_82.setFont(font)
        self.pushButton_82.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_82.setObjectName("pushButton_82")
        self.pushButton_80 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_80.setGeometry(QtCore.QRect(680, 340, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_80.setFont(font)
        self.pushButton_80.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_80.setObjectName("pushButton_80")
        self.pushButton_81 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_81.setGeometry(QtCore.QRect(680, 580, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_81.setFont(font)
        self.pushButton_81.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_81.setObjectName("pushButton_81")
        self.pushButton_83 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_83.setGeometry(QtCore.QRect(680, 660, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_83.setFont(font)
        self.pushButton_83.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_83.setObjectName("pushButton_83")
        self.os_in2 = QtWidgets.QTextEdit(self.page_5)
        self.os_in2.setGeometry(QtCore.QRect(110, 130, 211, 31))
        self.os_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.os_in2.setObjectName("os_in2")
        self.ram_in2 = QtWidgets.QTextEdit(self.page_5)
        self.ram_in2.setGeometry(QtCore.QRect(110, 190, 211, 31))
        self.ram_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ram_in2.setObjectName("ram_in2")
        self.core_in2 = QtWidgets.QTextEdit(self.page_5)
        self.core_in2.setGeometry(QtCore.QRect(110, 250, 211, 31))
        self.core_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.core_in2.setObjectName("core_in2")
        self.frequency_in2 = QtWidgets.QTextEdit(self.page_5)
        self.frequency_in2.setGeometry(QtCore.QRect(110, 310, 211, 31))
        self.frequency_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frequency_in2.setObjectName("frequency_in2")
        self.storage_in2 = QtWidgets.QTextEdit(self.page_5)
        self.storage_in2.setGeometry(QtCore.QRect(110, 380, 211, 31))
        self.storage_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.storage_in2.setObjectName("storage_in2")
        self.bandwidth_in2 = QtWidgets.QTextEdit(self.page_5)
        self.bandwidth_in2.setGeometry(QtCore.QRect(110, 440, 211, 31))
        self.bandwidth_in2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bandwidth_in2.setObjectName("bandwidth_in2")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.graphicsView_17 = QtWidgets.QGraphicsView(self.page_6)
        self.graphicsView_17.setGeometry(QtCore.QRect(80, 30, 491, 601))
        self.graphicsView_17.setObjectName("graphicsView_17")
        self.line_13 = QtWidgets.QFrame(self.page_6)
        self.line_13.setGeometry(QtCore.QRect(110, 100, 421, 20))
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_156 = QtWidgets.QLabel(self.page_6)
        self.label_156.setGeometry(QtCore.QRect(300, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_156.setFont(font)
        self.label_156.setObjectName("label_156")
        self.label_157 = QtWidgets.QLabel(self.page_6)
        self.label_157.setGeometry(QtCore.QRect(340, 150, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_157.setFont(font)
        self.label_157.setObjectName("label_157")
        self.label_158 = QtWidgets.QLabel(self.page_6)
        self.label_158.setGeometry(QtCore.QRect(230, 160, 55, 16))
        self.label_158.setObjectName("label_158")
        self.label_159 = QtWidgets.QLabel(self.page_6)
        self.label_159.setGeometry(QtCore.QRect(340, 200, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_159.setFont(font)
        self.label_159.setObjectName("label_159")
        self.label_160 = QtWidgets.QLabel(self.page_6)
        self.label_160.setGeometry(QtCore.QRect(230, 210, 55, 16))
        self.label_160.setObjectName("label_160")
        self.label_161 = QtWidgets.QLabel(self.page_6)
        self.label_161.setGeometry(QtCore.QRect(340, 250, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_161.setFont(font)
        self.label_161.setObjectName("label_161")
        self.label_162 = QtWidgets.QLabel(self.page_6)
        self.label_162.setGeometry(QtCore.QRect(230, 260, 55, 16))
        self.label_162.setObjectName("label_162")
        self.label_163 = QtWidgets.QLabel(self.page_6)
        self.label_163.setGeometry(QtCore.QRect(340, 300, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_163.setFont(font)
        self.label_163.setObjectName("label_163")
        self.label_164 = QtWidgets.QLabel(self.page_6)
        self.label_164.setGeometry(QtCore.QRect(230, 310, 55, 16))
        self.label_164.setObjectName("label_164")
        self.label_165 = QtWidgets.QLabel(self.page_6)
        self.label_165.setGeometry(QtCore.QRect(340, 350, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_165.setFont(font)
        self.label_165.setObjectName("label_165")
        self.label_166 = QtWidgets.QLabel(self.page_6)
        self.label_166.setGeometry(QtCore.QRect(230, 360, 55, 16))
        self.label_166.setObjectName("label_166")
        self.label_167 = QtWidgets.QLabel(self.page_6)
        self.label_167.setGeometry(QtCore.QRect(340, 400, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_167.setFont(font)
        self.label_167.setObjectName("label_167")
        self.label_168 = QtWidgets.QLabel(self.page_6)
        self.label_168.setGeometry(QtCore.QRect(230, 410, 55, 16))
        self.label_168.setObjectName("label_168")
        self.pushButton_78 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_78.setGeometry(QtCore.QRect(680, 490, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_78.setFont(font)
        self.pushButton_78.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_78.setObjectName("pushButton_78")
        self.pushButton_75 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_75.setGeometry(QtCore.QRect(680, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_75.setFont(font)
        self.pushButton_75.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_75.setObjectName("pushButton_75")
        self.pushButton_77 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_77.setGeometry(QtCore.QRect(680, 650, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_77.setFont(font)
        self.pushButton_77.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_77.setObjectName("pushButton_77")
        self.pushButton_73 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_73.setGeometry(QtCore.QRect(680, 250, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_73.setFont(font)
        self.pushButton_73.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_73.setObjectName("pushButton_73")
        self.pushButton_74 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_74.setGeometry(QtCore.QRect(680, 330, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_74.setFont(font)
        self.pushButton_74.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_74.setObjectName("pushButton_74")
        self.wallet_btn_11 = QtWidgets.QPushButton(self.page_6)
        self.wallet_btn_11.setGeometry(QtCore.QRect(680, 170, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wallet_btn_11.setFont(font)
        self.wallet_btn_11.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.wallet_btn_11.setObjectName("wallet_btn_11")
        self.sabtenam_btn3_11 = QtWidgets.QPushButton(self.page_6)
        self.sabtenam_btn3_11.setGeometry(QtCore.QRect(680, 100, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabtenam_btn3_11.setFont(font)
        self.sabtenam_btn3_11.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.sabtenam_btn3_11.setObjectName("sabtenam_btn3_11")
        self.login_btn2_15 = QtWidgets.QPushButton(self.page_6)
        self.login_btn2_15.setGeometry(QtCore.QRect(680, 20, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn2_15.setFont(font)
        self.login_btn2_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn2_15.setObjectName("login_btn2_15")
        self.pushButton_76 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_76.setGeometry(QtCore.QRect(680, 410, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_76.setFont(font)
        self.pushButton_76.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_76.setObjectName("pushButton_76")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.pushButton_49 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_49.setGeometry(QtCore.QRect(680, 330, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_50.setGeometry(QtCore.QRect(680, 250, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_50.setObjectName("pushButton_50")
        self.wallet_btn_7 = QtWidgets.QPushButton(self.page_7)
        self.wallet_btn_7.setGeometry(QtCore.QRect(680, 170, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wallet_btn_7.setFont(font)
        self.wallet_btn_7.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.wallet_btn_7.setObjectName("wallet_btn_7")
        self.pushButton_51 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_51.setGeometry(QtCore.QRect(680, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_52 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_52.setGeometry(QtCore.QRect(680, 490, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_52.setObjectName("pushButton_52")
        self.sabtenam_btn3_7 = QtWidgets.QPushButton(self.page_7)
        self.sabtenam_btn3_7.setGeometry(QtCore.QRect(680, 100, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabtenam_btn3_7.setFont(font)
        self.sabtenam_btn3_7.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.sabtenam_btn3_7.setObjectName("sabtenam_btn3_7")
        self.pushButton_53 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_53.setGeometry(QtCore.QRect(680, 410, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_53.setObjectName("pushButton_53")
        self.login_btn2_7 = QtWidgets.QPushButton(self.page_7)
        self.login_btn2_7.setGeometry(QtCore.QRect(680, 20, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn2_7.setFont(font)
        self.login_btn2_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn2_7.setObjectName("login_btn2_7")
        self.graphicsView_18 = QtWidgets.QGraphicsView(self.page_7)
        self.graphicsView_18.setGeometry(QtCore.QRect(100, 20, 491, 611))
        self.graphicsView_18.setObjectName("graphicsView_18")
        self.label_169 = QtWidgets.QLabel(self.page_7)
        self.label_169.setGeometry(QtCore.QRect(460, 170, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_169.setFont(font)
        self.label_169.setObjectName("label_169")
        self.label_170 = QtWidgets.QLabel(self.page_7)
        self.label_170.setGeometry(QtCore.QRect(480, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_170.setFont(font)
        self.label_170.setObjectName("label_170")
        self.line_14 = QtWidgets.QFrame(self.page_7)
        self.line_14.setGeometry(QtCore.QRect(130, 90, 421, 20))
        self.line_14.setLineWidth(2)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_171 = QtWidgets.QLabel(self.page_7)
        self.label_171.setGeometry(QtCore.QRect(370, 260, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_171.setFont(font)
        self.label_171.setObjectName("label_171")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 410, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_54 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_54.setGeometry(QtCore.QRect(680, 650, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_54.setObjectName("pushButton_54")
        self.os_name = QtWidgets.QTextEdit(self.page_7)
        self.os_name.setGeometry(QtCore.QRect(170, 170, 151, 31))
        self.os_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.os_name.setObjectName("os_name")
        self.size_snapshot = QtWidgets.QTextEdit(self.page_7)
        self.size_snapshot.setGeometry(QtCore.QRect(170, 260, 151, 31))
        self.size_snapshot.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.size_snapshot.setObjectName("size_snapshot")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.sabtenam_btn3_8 = QtWidgets.QPushButton(self.page_8)
        self.sabtenam_btn3_8.setGeometry(QtCore.QRect(680, 110, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabtenam_btn3_8.setFont(font)
        self.sabtenam_btn3_8.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.sabtenam_btn3_8.setObjectName("sabtenam_btn3_8")
        self.wallet_btn_8 = QtWidgets.QPushButton(self.page_8)
        self.wallet_btn_8.setGeometry(QtCore.QRect(680, 180, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wallet_btn_8.setFont(font)
        self.wallet_btn_8.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.wallet_btn_8.setObjectName("wallet_btn_8")
        self.pushButton_55 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_55.setGeometry(QtCore.QRect(680, 500, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_55.setFont(font)
        self.pushButton_55.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_56 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_56.setGeometry(QtCore.QRect(680, 660, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_56.setFont(font)
        self.pushButton_56.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_57 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_57.setGeometry(QtCore.QRect(680, 580, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_58 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_58.setGeometry(QtCore.QRect(680, 340, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_58.setFont(font)
        self.pushButton_58.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_59 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_59.setGeometry(QtCore.QRect(680, 260, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_59.setFont(font)
        self.pushButton_59.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_59.setObjectName("pushButton_59")
        self.login_btn2_8 = QtWidgets.QPushButton(self.page_8)
        self.login_btn2_8.setGeometry(QtCore.QRect(680, 30, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn2_8.setFont(font)
        self.login_btn2_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn2_8.setObjectName("login_btn2_8")
        self.pushButton_60 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_60.setGeometry(QtCore.QRect(680, 420, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_60.setFont(font)
        self.pushButton_60.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_60.setObjectName("pushButton_60")
        self.label_172 = QtWidgets.QLabel(self.page_8)
        self.label_172.setGeometry(QtCore.QRect(510, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_172.setFont(font)
        self.label_172.setObjectName("label_172")
        self.textEdit = QtWidgets.QTextEdit(self.page_8)
        self.textEdit.setGeometry(QtCore.QRect(80, 120, 521, 221))
        self.textEdit.setObjectName("textEdit")
        self.line_15 = QtWidgets.QFrame(self.page_8)
        self.line_15.setGeometry(QtCore.QRect(80, 80, 531, 20))
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.label_173 = QtWidgets.QLabel(self.page_8)
        self.label_173.setGeometry(QtCore.QRect(370, 130, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_173.setFont(font)
        self.label_173.setObjectName("label_173")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 360, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.line_16 = QtWidgets.QFrame(self.page_8)
        self.line_16.setGeometry(QtCore.QRect(70, 440, 531, 20))
        self.line_16.setLineWidth(2)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.label_174 = QtWidgets.QLabel(self.page_8)
        self.label_174.setGeometry(QtCore.QRect(340, 410, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_174.setFont(font)
        self.label_174.setObjectName("label_174")
        self.textEdit_2 = QtWidgets.QTextEdit(self.page_8)
        self.textEdit_2.setGeometry(QtCore.QRect(80, 480, 521, 221))
        self.textEdit_2.setObjectName("textEdit_2")
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.sabtenam_btn3_9 = QtWidgets.QPushButton(self.page_9)
        self.sabtenam_btn3_9.setGeometry(QtCore.QRect(680, 110, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabtenam_btn3_9.setFont(font)
        self.sabtenam_btn3_9.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.sabtenam_btn3_9.setObjectName("sabtenam_btn3_9")
        self.pushButton_61 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_61.setGeometry(QtCore.QRect(680, 260, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_61.setFont(font)
        self.pushButton_61.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_62 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_62.setGeometry(QtCore.QRect(680, 340, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_62.setFont(font)
        self.pushButton_62.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_62.setObjectName("pushButton_62")
        self.wallet_btn_9 = QtWidgets.QPushButton(self.page_9)
        self.wallet_btn_9.setGeometry(QtCore.QRect(680, 180, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wallet_btn_9.setFont(font)
        self.wallet_btn_9.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.wallet_btn_9.setObjectName("wallet_btn_9")
        self.login_btn2_9 = QtWidgets.QPushButton(self.page_9)
        self.login_btn2_9.setGeometry(QtCore.QRect(680, 30, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn2_9.setFont(font)
        self.login_btn2_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn2_9.setObjectName("login_btn2_9")
        self.pushButton_63 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_63.setGeometry(QtCore.QRect(680, 500, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_63.setFont(font)
        self.pushButton_63.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_64 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_64.setGeometry(QtCore.QRect(680, 580, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_64.setFont(font)
        self.pushButton_64.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_65 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_65.setGeometry(QtCore.QRect(680, 660, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_65.setFont(font)
        self.pushButton_65.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_65.setObjectName("pushButton_65")
        self.pushButton_66 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_66.setGeometry(QtCore.QRect(680, 420, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_66.setFont(font)
        self.pushButton_66.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_66.setObjectName("pushButton_66")
        self.label_175 = QtWidgets.QLabel(self.page_9)
        self.label_175.setGeometry(QtCore.QRect(450, 180, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_175.setFont(font)
        self.label_175.setObjectName("label_175")
        self.label_176 = QtWidgets.QLabel(self.page_9)
        self.label_176.setGeometry(QtCore.QRect(470, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_176.setFont(font)
        self.label_176.setObjectName("label_176")
        self.graphicsView_19 = QtWidgets.QGraphicsView(self.page_9)
        self.graphicsView_19.setGeometry(QtCore.QRect(80, 40, 521, 611))
        self.graphicsView_19.setObjectName("graphicsView_19")
        self.line_17 = QtWidgets.QFrame(self.page_9)
        self.line_17.setGeometry(QtCore.QRect(120, 100, 461, 20))
        self.line_17.setLineWidth(2)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.label_177 = QtWidgets.QLabel(self.page_9)
        self.label_177.setGeometry(QtCore.QRect(340, 60, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_177.setFont(font)
        self.label_177.setObjectName("label_177")
        self.label_178 = QtWidgets.QLabel(self.page_9)
        self.label_178.setGeometry(QtCore.QRect(350, 160, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_178.setFont(font)
        self.label_178.setObjectName("label_178")
        self.label_179 = QtWidgets.QLabel(self.page_9)
        self.label_179.setGeometry(QtCore.QRect(350, 240, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_179.setFont(font)
        self.label_179.setObjectName("label_179")
        self.label_180 = QtWidgets.QLabel(self.page_9)
        self.label_180.setGeometry(QtCore.QRect(350, 330, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_180.setFont(font)
        self.label_180.setObjectName("label_180")
        self.label_181 = QtWidgets.QLabel(self.page_9)
        self.label_181.setGeometry(QtCore.QRect(320, 420, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_181.setFont(font)
        self.label_181.setObjectName("label_181")
        self.login_btn2_10 = QtWidgets.QPushButton(self.page_9)
        self.login_btn2_10.setGeometry(QtCore.QRect(150, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn2_10.setFont(font)
        self.login_btn2_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn2_10.setObjectName("login_btn2_10")
        self.login_btn2_11 = QtWidgets.QPushButton(self.page_9)
        self.login_btn2_11.setGeometry(QtCore.QRect(150, 230, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn2_11.setFont(font)
        self.login_btn2_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn2_11.setObjectName("login_btn2_11")
        self.login_btn2_12 = QtWidgets.QPushButton(self.page_9)
        self.login_btn2_12.setGeometry(QtCore.QRect(150, 320, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn2_12.setFont(font)
        self.login_btn2_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn2_12.setObjectName("login_btn2_12")
        self.login_btn2_13 = QtWidgets.QPushButton(self.page_9)
        self.login_btn2_13.setGeometry(QtCore.QRect(150, 410, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn2_13.setFont(font)
        self.login_btn2_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn2_13.setObjectName("login_btn2_13")
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.login_btn2_14 = QtWidgets.QPushButton(self.page_10)
        self.login_btn2_14.setGeometry(QtCore.QRect(680, 20, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_btn2_14.setFont(font)
        self.login_btn2_14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.login_btn2_14.setObjectName("login_btn2_14")
        self.pushButton_67 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_67.setGeometry(QtCore.QRect(680, 330, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_67.setFont(font)
        self.pushButton_67.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_68 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_68.setGeometry(QtCore.QRect(680, 410, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_68.setFont(font)
        self.pushButton_68.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_68.setObjectName("pushButton_68")
        self.pushButton_69 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_69.setGeometry(QtCore.QRect(680, 650, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_69.setFont(font)
        self.pushButton_69.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_69.setObjectName("pushButton_69")
        self.pushButton_70 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_70.setGeometry(QtCore.QRect(680, 250, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_70.setFont(font)
        self.pushButton_70.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_70.setObjectName("pushButton_70")
        self.pushButton_71 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_71.setGeometry(QtCore.QRect(680, 490, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_71.setFont(font)
        self.pushButton_71.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_71.setObjectName("pushButton_71")
        self.pushButton_72 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_72.setGeometry(QtCore.QRect(680, 570, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_72.setFont(font)
        self.pushButton_72.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_72.setObjectName("pushButton_72")
        self.wallet_btn_10 = QtWidgets.QPushButton(self.page_10)
        self.wallet_btn_10.setGeometry(QtCore.QRect(680, 170, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wallet_btn_10.setFont(font)
        self.wallet_btn_10.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.wallet_btn_10.setObjectName("wallet_btn_10")
        self.sabtenam_btn3_10 = QtWidgets.QPushButton(self.page_10)
        self.sabtenam_btn3_10.setGeometry(QtCore.QRect(680, 100, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabtenam_btn3_10.setFont(font)
        self.sabtenam_btn3_10.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.sabtenam_btn3_10.setObjectName("sabtenam_btn3_10")
        self.line_18 = QtWidgets.QFrame(self.page_10)
        self.line_18.setGeometry(QtCore.QRect(80, 60, 531, 20))
        self.line_18.setLineWidth(2)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.label_182 = QtWidgets.QLabel(self.page_10)
        self.label_182.setGeometry(QtCore.QRect(460, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_182.setFont(font)
        self.label_182.setObjectName("label_182")
        self.textEdit_3 = QtWidgets.QTextEdit(self.page_10)
        self.textEdit_3.setGeometry(QtCore.QRect(80, 100, 521, 591))
        self.textEdit_3.setObjectName("textEdit_3")
        self.stackedWidget.addWidget(self.page_10)
        t.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(t)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 936, 26))
        self.menuBar.setObjectName("menuBar")
        t.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(t)
        self.mainToolBar.setObjectName("mainToolBar")
        t.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(t)
        self.statusBar.setObjectName("statusBar")
        t.setStatusBar(self.statusBar)

        self.retranslateUi(t)
        self.stackedWidget.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(t)

    def retranslateUi(self, t):
        _translate = QtCore.QCoreApplication.translate
        t.setWindowTitle(_translate("t", "t"))
        self.groupBox_2.setTitle(_translate("t", "ورود"))
        self.label_6.setText(_translate("t", "نام کاربری"))
        self.login_btn1.setText(_translate("t", "ورود"))
        self.label_8.setText(_translate("t", "رمز عبور"))
        self.sabtenam_btn1.setText(_translate("t", "ثبت نام"))
        self.groupBox.setTitle(_translate("t", "اطلاعات کاربر"))
        self.label_2.setText(_translate("t", "نام خانوادگی"))
        self.label.setText(_translate("t", "نام"))
        self.label_3.setText(_translate("t", "کد ملی"))
        self.label_4.setText(_translate("t", "آدرس ایمیل"))
        self.label_5.setText(_translate("t", "رمز  عبور"))
        self.sabtenam_btn2.setText(_translate("t", "ثبت نام"))
        self.snap_btn1.setText(_translate("t", " snapshot"))
        self.taghir_btn1.setText(_translate("t", "تغییر مشخصات منبع"))
        self.ijad_btn1.setText(_translate("t", "ایجاد منبع"))
        self.sabtenam_btn3.setText(_translate("t", "ثبت نام"))
        self.price_btn1.setText(_translate("t", "مشاهده قیمت منابع"))
        self.login_btn4.setText(_translate("t", "ورود"))
        self.ticket_btn1.setText(_translate("t", "ارسال تیکت"))
        self.wallet_btn1.setText(_translate("t", "کیف پول"))
        self.gozaresh_btn1.setText(_translate("t", "لیست گزارش ها"))
        self.label_9.setText(_translate("t", "کیف پول"))
        self.afzayesh_mojodi_btn.setText(_translate("t", "افزایش موجودی"))
        self.label_16.setText(_translate("t", "مصرف این ماه"))
        self.label_15.setText(_translate("t", "ریال"))
        self.label_17.setText(_translate("t", "موجودی"))
        self.label_14.setText(_translate("t", "ریال"))
        self.label_11.setText(_translate("t", "سیستم عامل"))
        self.label_12.setText(_translate("t", "RAMظرفیت "))
        self.label_13.setText(_translate("t", "تعداد هسته"))
        self.label_18.setText(_translate("t", "فرکانس cpu"))
        self.label_19.setText(_translate("t", "فضای ذخیره سازی"))
        self.label_20.setText(_translate("t", "پهنای باند شبکه"))
        self.label_21.setText(_translate("t", "TextLabel"))
        self.label_22.setText(_translate("t", "TextLabel"))
        self.label_23.setText(_translate("t", "TextLabel"))
        self.label_24.setText(_translate("t", "TextLabel"))
        self.label_25.setText(_translate("t", "TextLabel"))
        self.label_26.setText(_translate("t", "TextLabel"))
        self.label_38.setText(_translate("t", "TextLabel"))
        self.label_125.setText(_translate("t", "سیستم عامل"))
        self.label_33.setText(_translate("t", "TextLabel"))
        self.label_32.setText(_translate("t", "TextLabel"))
        self.label_36.setText(_translate("t", "پهنای باند شبکه"))
        self.label_126.setText(_translate("t", "TextLabel"))
        self.label_34.setText(_translate("t", "TextLabel"))
        self.label_31.setText(_translate("t", "فرکانس cpu"))
        self.label_27.setText(_translate("t", "فضای ذخیره سازی"))
        self.label_30.setText(_translate("t", "RAMظرفیت "))
        self.label_28.setText(_translate("t", "تعداد هسته"))
        self.label_29.setText(_translate("t", "TextLabel"))
        self.label_40.setText(_translate("t", "فضای ذخیره سازی"))
        self.label_41.setText(_translate("t", "تعداد هسته"))
        self.label_42.setText(_translate("t", "TextLabel"))
        self.label_43.setText(_translate("t", "RAMظرفیت "))
        self.label_44.setText(_translate("t", "فرکانس cpu"))
        self.label_45.setText(_translate("t", "TextLabel"))
        self.label_46.setText(_translate("t", "TextLabel"))
        self.label_47.setText(_translate("t", "TextLabel"))
        self.label_49.setText(_translate("t", "پهنای باند شبکه"))
        self.label_50.setText(_translate("t", "سیستم عامل"))
        self.label_51.setText(_translate("t", "TextLabel"))
        self.label_52.setText(_translate("t", "TextLabel"))
        self.label_53.setText(_translate("t", "فضای ذخیره سازی"))
        self.label_54.setText(_translate("t", "تعداد هسته"))
        self.label_55.setText(_translate("t", "TextLabel"))
        self.label_56.setText(_translate("t", "RAMظرفیت "))
        self.label_57.setText(_translate("t", "فرکانس cpu"))
        self.label_58.setText(_translate("t", "TextLabel"))
        self.label_59.setText(_translate("t", "TextLabel"))
        self.label_60.setText(_translate("t", "TextLabel"))
        self.label_62.setText(_translate("t", "پهنای باند شبکه"))
        self.label_63.setText(_translate("t", "سیستم عامل"))
        self.label_64.setText(_translate("t", "TextLabel"))
        self.label_65.setText(_translate("t", "TextLabel"))
        self.label_128.setText(_translate("t", "فضای ذخیره سازی"))
        self.label_129.setText(_translate("t", "تعداد هسته"))
        self.label_130.setText(_translate("t", "TextLabel"))
        self.label_131.setText(_translate("t", "RAMظرفیت "))
        self.label_132.setText(_translate("t", "فرکانس cpu"))
        self.label_133.setText(_translate("t", "TextLabel"))
        self.label_134.setText(_translate("t", "TextLabel"))
        self.label_135.setText(_translate("t", "TextLabel"))
        self.label_137.setText(_translate("t", "پهنای باند شبکه"))
        self.label_138.setText(_translate("t", "سیستم عامل"))
        self.label_139.setText(_translate("t", "TextLabel"))
        self.label_140.setText(_translate("t", "TextLabel"))
        self.label_141.setText(_translate("t", "فضای ذخیره سازی"))
        self.label_142.setText(_translate("t", "تعداد هسته"))
        self.label_143.setText(_translate("t", "TextLabel"))
        self.label_144.setText(_translate("t", "RAMظرفیت "))
        self.label_145.setText(_translate("t", "فرکانس cpu"))
        self.label_146.setText(_translate("t", "TextLabel"))
        self.label_147.setText(_translate("t", "TextLabel"))
        self.label_148.setText(_translate("t", "TextLabel"))
        self.label_150.setText(_translate("t", "پهنای باند شبکه"))
        self.label_151.setText(_translate("t", "سیستم عامل"))
        self.label_152.setText(_translate("t", "TextLabel"))
        self.label_153.setText(_translate("t", "TextLabel"))
        self.checkBox.setText(_translate("t", "منبع 1"))
        self.checkBox_2.setText(_translate("t", "منبع 2"))
        self.checkBox_3.setText(_translate("t", "منبع 3"))
        self.checkBox_4.setText(_translate("t", "منبع 4"))
        self.checkBox_5.setText(_translate("t", "منبع 5"))
        self.checkBox_6.setText(_translate("t", "منبع 6"))
        self.ijad_btn2.setText(_translate("t", "ایجاد منبع"))
        self.taghir_btn2.setText(_translate("t", "تغییر مشخصات منبع"))
        self.ticket_btn2.setText(_translate("t", "ارسال تیکت"))
        self.price_btn2.setText(_translate("t", "مشاهده قیمت منابع"))
        self.sabtenam_btn4.setText(_translate("t", "ثبت نام"))
        self.gozaresh_btn2.setText(_translate("t", "لیست گزارش ها"))
        self.wallet_btn2.setText(_translate("t", "کیف پول"))
        self.login_btn3.setText(_translate("t", "ورود"))
        self.snap_btn2.setText(_translate("t", " snapshot"))
        self.label_48.setText(_translate("t", "فضای ذخیره سازی"))
        self.label_61.setText(_translate("t", "تعداد هسته"))
        self.label_127.setText(_translate("t", "RAMظرفیت "))
        self.label_136.setText(_translate("t", "فرکانس cpu"))
        self.label_149.setText(_translate("t", "پهنای باند شبکه"))
        self.label_154.setText(_translate("t", "سیستم عامل"))
        self.label_155.setText(_translate("t", "مشخصات منبع جدید"))
        self.pushButton_3.setText(_translate("t", "اعمال تغییرات"))
        self.pushButton_84.setText(_translate("t", " snapshot"))
        self.login_btn2_16.setText(_translate("t", "ورود"))
        self.pushButton_79.setText(_translate("t", "ایجاد منبع"))
        self.wallet_btn_12.setText(_translate("t", "کیف پول"))
        self.sabtenam_btn3_12.setText(_translate("t", "ثبت نام"))
        self.pushButton_82.setText(_translate("t", "مشاهده قیمت منابع"))
        self.pushButton_80.setText(_translate("t", "تغییر مشخصات منبع"))
        self.pushButton_81.setText(_translate("t", "ارسال تیکت"))
        self.pushButton_83.setText(_translate("t", "لیست گزارش ها"))
        self.label_156.setText(_translate("t", "قیمت منابع موجود"))
        self.label_157.setText(_translate("t", "منبع 1"))
        self.label_158.setText(_translate("t", "TextLabel"))
        self.label_159.setText(_translate("t", "منبع 2"))
        self.label_160.setText(_translate("t", "TextLabel"))
        self.label_161.setText(_translate("t", "منبع 3"))
        self.label_162.setText(_translate("t", "TextLabel"))
        self.label_163.setText(_translate("t", "منبع 4"))
        self.label_164.setText(_translate("t", "TextLabel"))
        self.label_165.setText(_translate("t", "منبع 5"))
        self.label_166.setText(_translate("t", "TextLabel"))
        self.label_167.setText(_translate("t", "منبع 6"))
        self.label_168.setText(_translate("t", "TextLabel"))
        self.pushButton_78.setText(_translate("t", " snapshot"))
        self.pushButton_75.setText(_translate("t", "ارسال تیکت"))
        self.pushButton_77.setText(_translate("t", "لیست گزارش ها"))
        self.pushButton_73.setText(_translate("t", "ایجاد منبع"))
        self.pushButton_74.setText(_translate("t", "تغییر مشخصات منبع"))
        self.wallet_btn_11.setText(_translate("t", "کیف پول"))
        self.sabtenam_btn3_11.setText(_translate("t", "ثبت نام"))
        self.login_btn2_15.setText(_translate("t", "ورود"))
        self.pushButton_76.setText(_translate("t", "مشاهده قیمت منابع"))
        self.pushButton_49.setText(_translate("t", "تغییر مشخصات منبع"))
        self.pushButton_50.setText(_translate("t", "ایجاد منبع"))
        self.wallet_btn_7.setText(_translate("t", "کیف پول"))
        self.pushButton_51.setText(_translate("t", "ارسال تیکت"))
        self.pushButton_52.setText(_translate("t", " snapshot"))
        self.sabtenam_btn3_7.setText(_translate("t", "ثبت نام"))
        self.pushButton_53.setText(_translate("t", "مشاهده قیمت منابع"))
        self.login_btn2_7.setText(_translate("t", "ورود"))
        self.label_169.setText(_translate("t", "نام منبع"))
        self.label_170.setText(_translate("t", "snapshot"))
        self.label_171.setText(_translate("t", "سایز اسنپ شات"))
        self.pushButton_4.setText(_translate("t", "گرفتن اسنپ شات"))
        self.pushButton_54.setText(_translate("t", "لیست گزارش ها"))
        self.sabtenam_btn3_8.setText(_translate("t", "ثبت نام"))
        self.wallet_btn_8.setText(_translate("t", "کیف پول"))
        self.pushButton_55.setText(_translate("t", " snapshot"))
        self.pushButton_56.setText(_translate("t", "لیست گزارش ها"))
        self.pushButton_57.setText(_translate("t", "ارسال تیکت"))
        self.pushButton_58.setText(_translate("t", "تغییر مشخصات منبع"))
        self.pushButton_59.setText(_translate("t", "ایجاد منبع"))
        self.login_btn2_8.setText(_translate("t", "ورود"))
        self.pushButton_60.setText(_translate("t", "مشاهده قیمت منابع"))
        self.label_172.setText(_translate("t", "تیکت"))
        self.label_173.setText(_translate("t", "مشکل خود را شرح دهید"))
        self.pushButton_5.setText(_translate("t", "ارسال تیکت"))
        self.label_174.setText(_translate("t", "مشاهده ی پاسخ تیکت"))
        self.sabtenam_btn3_9.setText(_translate("t", "ثبت نام"))
        self.pushButton_61.setText(_translate("t", "ایجاد منبع"))
        self.pushButton_62.setText(_translate("t", "تغییر مشخصات منبع"))
        self.wallet_btn_9.setText(_translate("t", "کیف پول"))
        self.login_btn2_9.setText(_translate("t", "ورود"))
        self.pushButton_63.setText(_translate("t", " snapshot"))
        self.pushButton_64.setText(_translate("t", "ارسال تیکت"))
        self.pushButton_65.setText(_translate("t", "لیست گزارش ها"))
        self.pushButton_66.setText(_translate("t", "مشاهده قیمت منابع"))
        self.label_175.setText(_translate("t", "نام منبع"))
        self.label_176.setText(_translate("t", "snapshot"))
        self.label_177.setText(_translate("t", "لیست گزارش ها"))
        self.label_178.setText(_translate("t", "لیست کاربران با مشخصات آنها"))
        self.label_179.setText(_translate("t", "منابع هر کاربر"))
        self.label_180.setText(_translate("t", "لیست منابع موجود در سامانه"))
        self.label_181.setText(_translate("t", "مشاهده ی تمام تیکت هابراساس وضعیت"))
        self.login_btn2_10.setText(_translate("t", "مشاهده"))
        self.login_btn2_11.setText(_translate("t", "مشاهده"))
        self.login_btn2_12.setText(_translate("t", "مشاهده"))
        self.login_btn2_13.setText(_translate("t", "مشاهده"))
        self.login_btn2_14.setText(_translate("t", "ورود"))
        self.pushButton_67.setText(_translate("t", "تغییر مشخصات منبع"))
        self.pushButton_68.setText(_translate("t", "مشاهده قیمت منابع"))
        self.pushButton_69.setText(_translate("t", "لیست گزارش ها"))
        self.pushButton_70.setText(_translate("t", "ایجاد منبع"))
        self.pushButton_71.setText(_translate("t", " snapshot"))
        self.pushButton_72.setText(_translate("t", "ارسال تیکت"))
        self.wallet_btn_10.setText(_translate("t", "کیف پول"))
        self.sabtenam_btn3_10.setText(_translate("t", "ثبت نام"))
        self.label_182.setText(_translate("t", "گزارش مربوطه"))
